import { Inter } from 'next/font/google';
import NavbarCommon from './components/global/NavbarCommon';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'react-toastify/dist/ReactToastify.min.css';
import './globals.css';
import { GlobalWrapper } from './GlobalWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalWrapper>
          <div className="bg-[#eaeaea]">{children}</div>
        </GlobalWrapper>
      </body>
    </html>
  );
}
