import { Inter } from 'next/font/google';
import './globals.css';
import NavbarCommon from './components/global/NavbarCommon';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'react-toastify/dist/ReactToastify.min.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarCommon />
        {children}
      </body>
    </html>
  );
}
